// @ts-check
/// <reference types="@actions/github-script" />

/**
 * Generates a standalone workflow-id XML comment marker for searchability.
 * This marker enables finding all items (issues, discussions, PRs, comments)
 * generated by a specific workflow.
 *
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Standalone workflow-id XML comment marker
 */
function generateWorkflowIdMarker(workflowId) {
  return `<!-- gh-aw-workflow-id: ${workflowId} -->`;
}

/**
 * Gets the workflow-id marker content (without XML comment wrapper) for searching.
 * This is used when searching for issues/discussions/PRs by workflow-id.
 *
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Workflow-id marker content for search queries
 */
function getWorkflowIdMarkerContent(workflowId) {
  return `gh-aw-workflow-id: ${workflowId}`;
}

/**
 * Generates an XML comment marker with agentic workflow metadata for traceability.
 * This marker enables searching and tracing back items generated by an agentic workflow.
 *
 * Note: This function is duplicated in messages_footer.cjs. While normally we would
 * consolidate to a shared module, importing messages_footer.cjs here would cause the
 * bundler to inline messages_core.cjs which contains 'GH_AW_SAFE_OUTPUT_MESSAGES:' in
 * a warning message, breaking tests that check for env var declarations.
 *
 * @param {string} workflowName - Name of the workflow
 * @param {string} runUrl - URL of the workflow run
 * @returns {string} XML comment marker with workflow metadata
 */
function generateXMLMarker(workflowName, runUrl) {
  // Read engine metadata from environment variables
  const engineId = process.env.GH_AW_ENGINE_ID || "";
  const engineVersion = process.env.GH_AW_ENGINE_VERSION || "";
  const engineModel = process.env.GH_AW_ENGINE_MODEL || "";
  const trackerId = process.env.GH_AW_TRACKER_ID || "";

  // Build the key-value pairs for the marker
  const parts = [];

  // Always include agentic-workflow name
  parts.push(`gh-aw-agentic-workflow: ${workflowName}`);

  // Add tracker-id if available (for searchability and tracing)
  if (trackerId) {
    parts.push(`gh-aw-tracker-id: ${trackerId}`);
  }

  // Add engine ID if available
  if (engineId) {
    parts.push(`engine: ${engineId}`);
  }

  // Add version if available
  if (engineVersion) {
    parts.push(`version: ${engineVersion}`);
  }

  // Add model if available
  if (engineModel) {
    parts.push(`model: ${engineModel}`);
  }

  // Always include run URL
  parts.push(`run: ${runUrl}`);

  // Return the XML comment marker
  return `<!-- ${parts.join(", ")} -->`;
}

/**
 * Generate footer for expired entity closing comments
 * @param {string} workflowName - Name of the workflow
 * @param {string} runUrl - URL of the workflow run
 * @param {string} workflowId - Workflow identifier
 * @returns {string} Footer text with workflow run link and XML markers
 */
function generateExpiredEntityFooter(workflowName, runUrl, workflowId) {
  let footer = `\n\n> Closed by [${workflowName}](${runUrl})`;

  // Add XML markers for searchability
  footer += "\n\n<!-- gh-aw-expired-comments -->";
  if (workflowId) {
    footer += "\n" + generateWorkflowIdMarker(workflowId);
  }
  footer += "\n" + generateXMLMarker(workflowName, runUrl);

  return footer;
}

module.exports = {
  generateXMLMarker,
  generateWorkflowIdMarker,
  getWorkflowIdMarkerContent,
  generateExpiredEntityFooter,
};
