#!/usr/bin/env bash
# Setup Action
# Copies activation job files to the agent environment
#
# This script copies JavaScript (.cjs) and JSON files from the js/ directory
# and shell scripts from the sh/ directory to the destination directory.
#
# The js/ and sh/ directories contain the source of truth for all JavaScript
# and shell script files. These files are manually edited and committed to git.
# They are NOT generated by a build process.
#
# At runtime, this script copies the files from actions/setup/js/ and 
# actions/setup/sh/ to /tmp/gh-aw/actions where workflows can access them.

set -e

# Helper: create directories with sudo on macOS where /opt is root-owned
create_dir() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sudo mkdir -p "$1"
    sudo chown -R "$(whoami)" "$1"
  else
    mkdir -p "$1"
  fi
}

# Get destination from input or use default
DESTINATION="${INPUT_DESTINATION:-/opt/gh-aw/actions}"

# Get safe-output-custom-tokens flag from input (default: false)
SAFE_OUTPUT_CUSTOM_TOKENS_ENABLED="${INPUT_SAFE_OUTPUT_CUSTOM_TOKENS:-false}"

echo "Copying activation files to ${DESTINATION}"
echo "Safe-output custom tokens support: ${SAFE_OUTPUT_CUSTOM_TOKENS_ENABLED}"

# Create destination directory if it doesn't exist
create_dir "${DESTINATION}"
echo "Created directory: ${DESTINATION}"

# Remove and recreate /tmp/gh-aw directory to ensure a clean state
rm -rf /tmp/gh-aw
mkdir -p /tmp/gh-aw
echo "Created /tmp/gh-aw directory"

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JS_SOURCE_DIR="${SCRIPT_DIR}/js"

echo "Script directory: ${SCRIPT_DIR}"
echo "Looking for JavaScript sources in: ${JS_SOURCE_DIR}"

# Debug: List the contents of the script directory to understand the file layout
echo "Contents of ${SCRIPT_DIR}:"
ls -la "${SCRIPT_DIR}" || echo "::warning::Failed to list ${SCRIPT_DIR}"

# Check if js directory exists
if [ ! -d "${JS_SOURCE_DIR}" ]; then
  echo "::error::JavaScript source directory not found: ${JS_SOURCE_DIR}"
  echo "::error::The js/ directory should contain the source of truth JavaScript files"
  echo "::error::These files should be committed to git in actions/setup/js/"
  
  # Additional debugging: show what's in the parent directory
  echo "Contents of parent directory $(dirname "${SCRIPT_DIR}"):"
  ls -la "$(dirname "${SCRIPT_DIR}")" || echo "::warning::Failed to list parent directory"
  
  exit 1
fi

# List files in js directory for debugging
echo "Files in ${JS_SOURCE_DIR}:"
ls -1 "${JS_SOURCE_DIR}" | head -10 || echo "::warning::Failed to list files in ${JS_SOURCE_DIR}"
FILE_COUNT_IN_DIR=$(ls -1 "${JS_SOURCE_DIR}" 2>/dev/null | wc -l)
echo "Found ${FILE_COUNT_IN_DIR} files in ${JS_SOURCE_DIR}"

# Copy all .cjs files from js/ to destination (excluding test files)
FILE_COUNT=0
for file in "${JS_SOURCE_DIR}"/*.cjs; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    # Skip test files
    if [[ "$filename" == *.test.cjs ]]; then
      echo "Skipping test file: ${filename}"
      continue
    fi
    cp "$file" "${DESTINATION}/${filename}"
    echo "Copied: ${filename}"
    FILE_COUNT=$((FILE_COUNT + 1))
  fi
done

# Copy any .json files as well
for file in "${JS_SOURCE_DIR}"/*.json; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    cp "$file" "${DESTINATION}/${filename}"
    echo "Copied: ${filename}"
    FILE_COUNT=$((FILE_COUNT + 1))
  fi
done

# Copy shell scripts from sh/ directory with executable permissions
SH_SOURCE_DIR="${SCRIPT_DIR}/sh"
if [ -d "${SH_SOURCE_DIR}" ]; then
  echo "Found shell scripts directory: ${SH_SOURCE_DIR}"
  for file in "${SH_SOURCE_DIR}"/*.sh; do
    if [ -f "$file" ]; then
      filename=$(basename "$file")
      cp "$file" "${DESTINATION}/${filename}"
      chmod +x "${DESTINATION}/${filename}"
      echo "Copied shell script: ${filename}"
      FILE_COUNT=$((FILE_COUNT + 1))
    fi
  done
else
  echo "No shell scripts directory found at ${SH_SOURCE_DIR}"
fi

echo "Successfully copied ${FILE_COUNT} files to ${DESTINATION}"

# Copy prompt markdown files to their expected directory
PROMPTS_DEST="/opt/gh-aw/prompts"
echo "Copying prompt markdown files to ${PROMPTS_DEST}"
create_dir "${PROMPTS_DEST}"

MD_SOURCE_DIR="${SCRIPT_DIR}/md"
PROMPT_COUNT=0
if [ -d "${MD_SOURCE_DIR}" ]; then
  echo "Found markdown prompts directory: ${MD_SOURCE_DIR}"
  for file in "${MD_SOURCE_DIR}"/*.md; do
    if [ -f "$file" ]; then
      filename=$(basename "$file")
      cp "$file" "${PROMPTS_DEST}/${filename}"
      echo "Copied prompt: ${filename}"
      PROMPT_COUNT=$((PROMPT_COUNT + 1))
    fi
  done
  echo "Successfully copied ${PROMPT_COUNT} prompt files to ${PROMPTS_DEST}"
else
  echo "::warning::No markdown prompts directory found at ${MD_SOURCE_DIR}"
fi

# Copy mcp-scripts files to their expected directory
MCP_SCRIPTS_DEST="/opt/gh-aw/mcp-scripts"
echo "Copying mcp-scripts files to ${MCP_SCRIPTS_DEST}"
create_dir "${MCP_SCRIPTS_DEST}"

MCP_SCRIPTS_FILES=(
  "mcp_scripts_bootstrap.cjs"
  "mcp_scripts_config_loader.cjs"
  "mcp_scripts_mcp_server.cjs"
  "mcp_scripts_mcp_server_http.cjs"
  "mcp_scripts_tool_factory.cjs"
  "mcp_scripts_validation.cjs"
  "mcp_server_core.cjs"
  "mcp_logger.cjs"
  "mcp_http_transport.cjs"
  "mcp_handler_shell.cjs"
  "mcp_handler_python.cjs"
  "mcp_handler_go.cjs"
  "mcp_handler_javascript.cjs"
  "read_buffer.cjs"
  "generate_mcp_scripts_config.cjs"
  "setup_globals.cjs"
  "error_helpers.cjs"
  "error_codes.cjs"
  "mcp_enhanced_errors.cjs"
  "shim.cjs"
  "mcp-scripts-runner.cjs"
)

MCP_SCRIPTS_COUNT=0
MCP_SCRIPTS_MISSING=()
for file in "${MCP_SCRIPTS_FILES[@]}"; do
  if [ -f "${JS_SOURCE_DIR}/${file}" ]; then
    cp "${JS_SOURCE_DIR}/${file}" "${MCP_SCRIPTS_DEST}/${file}"
    echo "Copied mcp-scripts: ${file}"
    MCP_SCRIPTS_COUNT=$((MCP_SCRIPTS_COUNT + 1))
  else
    echo "::error::MCP Scripts file not found: ${file}"
    MCP_SCRIPTS_MISSING+=("${file}")
  fi
done

if [ ${#MCP_SCRIPTS_MISSING[@]} -gt 0 ]; then
  echo "::error::Failed to copy ${#MCP_SCRIPTS_MISSING[@]} required mcp-scripts files:"
  for missing_file in "${MCP_SCRIPTS_MISSING[@]}"; do
    echo "::error::  - ${missing_file}"
  done
  echo "::error::Expected location: ${JS_SOURCE_DIR}"
  echo "::error::These files must exist in the repository for mcp-scripts to work"
  exit 1
fi

echo "Successfully copied ${MCP_SCRIPTS_COUNT} mcp-scripts files to ${MCP_SCRIPTS_DEST}"

# Copy safe-outputs files to their expected directory
SAFE_OUTPUTS_DEST="/opt/gh-aw/safeoutputs"
echo "Copying safe-outputs files to ${SAFE_OUTPUTS_DEST}"
create_dir "${SAFE_OUTPUTS_DEST}"

SAFE_OUTPUTS_FILES=(
  "safe_outputs_mcp_server.cjs"
  "safe_outputs_mcp_server_http.cjs"
  "safe_outputs_bootstrap.cjs"
  "safe_outputs_tools_loader.cjs"
  "safe_outputs_config.cjs"
  "safe_outputs_handlers.cjs"
  "safe_outputs_append.cjs"
  "mcp_server_core.cjs"
  "mcp_logger.cjs"
  "mcp_http_transport.cjs"
  "mcp_handler_python.cjs"
  "mcp_handler_shell.cjs"
  "mcp_handler_go.cjs"
  "mcp_handler_javascript.cjs"
  "read_buffer.cjs"
  "mcp_scripts_validation.cjs"
  "messages.cjs"
  "messages_core.cjs"
  "messages_footer.cjs"
  "messages_run_status.cjs"
  "messages_staged.cjs"
  "messages_close_discussion.cjs"
  "estimate_tokens.cjs"
  "generate_git_patch.cjs"
  "get_base_branch.cjs"
  "get_current_branch.cjs"
  "normalize_branch_name.cjs"
  "write_large_content_to_file.cjs"
  "generate_compact_schema.cjs"
  "setup_globals.cjs"
  "error_helpers.cjs"
  "error_codes.cjs"
  "git_helpers.cjs"
  "find_repo_checkout.cjs"
  "mcp_enhanced_errors.cjs"
  "comment_limit_helpers.cjs"
  "shim.cjs"
  "repo_helpers.cjs"
  "glob_pattern_helpers.cjs"
  "handler_auth.cjs"
  "missing_messages_helper.cjs"
  "firewall_blocked_domains.cjs"
  "missing_info_formatter.cjs"
  "sanitize_content_core.cjs"
  "markdown_code_region_balancer.cjs"
  "temporary_id.cjs"
)

SAFE_OUTPUTS_COUNT=0
SAFE_OUTPUTS_MISSING=()
for file in "${SAFE_OUTPUTS_FILES[@]}"; do
  if [ -f "${JS_SOURCE_DIR}/${file}" ]; then
    cp "${JS_SOURCE_DIR}/${file}" "${SAFE_OUTPUTS_DEST}/${file}"
    echo "Copied safe-outputs: ${file}"
    SAFE_OUTPUTS_COUNT=$((SAFE_OUTPUTS_COUNT + 1))
  elif [ -f "${DESTINATION}/${file}" ]; then
    # If file was already copied to main destination, copy from there
    cp "${DESTINATION}/${file}" "${SAFE_OUTPUTS_DEST}/${file}"
    echo "Copied safe-outputs (from destination): ${file}"
    SAFE_OUTPUTS_COUNT=$((SAFE_OUTPUTS_COUNT + 1))
  else
    echo "::error::Safe-outputs file not found: ${file}"
    SAFE_OUTPUTS_MISSING+=("${file}")
  fi
done

if [ ${#SAFE_OUTPUTS_MISSING[@]} -gt 0 ]; then
  echo "::error::Failed to copy ${#SAFE_OUTPUTS_MISSING[@]} required safe-outputs files:"
  for missing_file in "${SAFE_OUTPUTS_MISSING[@]}"; do
    echo "::error::  - ${missing_file}"
  done
  echo "::error::Expected locations: ${JS_SOURCE_DIR} or ${DESTINATION}"
  echo "::error::These files must exist in the repository for safe-outputs to work"
  exit 1
fi

# Copy the MCP server entry point to mcp-server.cjs (the name expected by MCP config)
if [ -f "${JS_SOURCE_DIR}/safe-outputs-mcp-server.cjs" ]; then
  cp "${JS_SOURCE_DIR}/safe-outputs-mcp-server.cjs" "${SAFE_OUTPUTS_DEST}/mcp-server.cjs"
  chmod +x "${SAFE_OUTPUTS_DEST}/mcp-server.cjs"
  echo "Copied safe-outputs MCP entry point: mcp-server.cjs"
  SAFE_OUTPUTS_COUNT=$((SAFE_OUTPUTS_COUNT + 1))
else
  echo "::warning::Safe-outputs MCP entry point not found: safe-outputs-mcp-server.cjs"
fi

# Copy safe_outputs_tools.json to tools.json (required by safe-outputs server)
if [ -f "${JS_SOURCE_DIR}/safe_outputs_tools.json" ]; then
  cp "${JS_SOURCE_DIR}/safe_outputs_tools.json" "${SAFE_OUTPUTS_DEST}/tools.json"
  echo "Copied safe-outputs tools definition: tools.json"
  SAFE_OUTPUTS_COUNT=$((SAFE_OUTPUTS_COUNT + 1))
else
  echo "::error::Safe-outputs tools definition not found: safe_outputs_tools.json"
  exit 1
fi

# Create empty config.json if it doesn't exist (required by safe-outputs server check)
# The actual config is optional and will be loaded from environment if provided
if [ ! -f "${SAFE_OUTPUTS_DEST}/config.json" ]; then
  echo "{}" > "${SAFE_OUTPUTS_DEST}/config.json"
  echo "Created empty config.json for safe-outputs server"
fi

echo "Successfully copied ${SAFE_OUTPUTS_COUNT} safe-outputs files to ${SAFE_OUTPUTS_DEST}"

# Install @actions/github package if any safe output uses a per-handler github-token.
# handler_auth.cjs needs getOctokit() from @actions/github to create a new Octokit
# instance when a handler has its own token (for cross-repo operations, project tokens, etc.).
if [ "${SAFE_OUTPUT_CUSTOM_TOKENS_ENABLED}" = "true" ]; then
  echo "Custom tokens enabled - installing @actions/github package in ${DESTINATION}..."
  cd "${DESTINATION}"

  # Check if npm is available
  if ! command -v npm &> /dev/null; then
    echo "::error::npm is not available. Cannot install @actions/github package."
    exit 1
  fi

  # Create a minimal package.json if it doesn't exist
  if [ ! -f "package.json" ]; then
    echo '{"private": true}' > package.json
  fi

  # Install @actions/github package
  npm install --no-save --loglevel=error @actions/github@^7.0.0 2>&1 | grep -v "npm WARN" || true
  if [ -d "node_modules/@actions/github" ]; then
    echo "✓ Successfully installed @actions/github package"
  else
    echo "::error::Failed to install @actions/github package"
    exit 1
  fi

  # Return to original directory
  cd - > /dev/null
else
  echo "Custom tokens not enabled - skipping @actions/github installation"
fi

# Set output
if [ -n "${GITHUB_OUTPUT}" ]; then
  echo "files_copied=${FILE_COUNT}" >> "${GITHUB_OUTPUT}"
  echo "mcp_scripts_files_copied=${MCP_SCRIPTS_COUNT}" >> "${GITHUB_OUTPUT}"
  echo "safe_outputs_files_copied=${SAFE_OUTPUTS_COUNT}" >> "${GITHUB_OUTPUT}"
  echo "prompt_files_copied=${PROMPT_COUNT}" >> "${GITHUB_OUTPUT}"
else
  echo "GITHUB_OUTPUT not set, skipping output"
fi
