name: Smoke Water

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  call-smoke-workflow-call:
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'water'
    uses: ./.github/workflows/smoke-workflow-call.lock.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      discussions: write
      issues: write
      pull-requests: write
